### PR TITLE
added german translation

### PR DESCRIPTION
**Pull request by jahangmar**

### CODE REVIEW

**Comment by JohnsonNicholas** [comment]
So I can merge this in, just with the caveat that I'm about to completely rewrite this file once I get through an annoying bit of blocking on designing something. Are you okay with that?

**Comment by jahangmar** [comment]
I'm not sure if I understand you. You are rewriting the translation files? What exactly are you asking me? You can do whatever you want with your mod.

**Comment by JohnsonNicholas** [comment]
I mean that I am rewriting the descriptions so that the translation will be
out of date in about a week or so

**Comment by jahangmar** [comment]
Okay, so my timing was bad. I can make a new version then.

**Pull request closed without merging**
